vich_uploader:
    db_driver: orm
    mappings:
        appart_image:
            uri_prefix: /images/appart
            upload_destination: '%kernel.project_dir%/public/images/appart'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
